oms/oms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext as _

from orders.views import OrderList, OrderDetails, OrderAdd, OrderEdit, OrderDelete, \
    ItemAdd, ItemEdit, ItemDelete, CommentAdd, CommentEdit, CommentDelete, Info, Stats, OrderSearch, Archive, \
    AddressDetails, AddressAdd, AddressEdit, AddressDelete

from users.views import UserList, Login, Logout, UserAdd, UserEdit, UserDelete


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

# Language
urlpatterns += i18n_patterns(
    path('', OrderList.as_view(), name='order_list'),
    path('archive/', Archive.as_view(), name='archive'),

    path('stats/', Stats.as_view(), name='stats'),
    path('info/', Info.as_view(), name='info'),
    path('order_details/<int:order_pk>/', OrderDetails.as_view(), name='order_details'),
    path('order_search/', OrderSearch.as_view(), name='order_search'),

    path('order_add/', OrderAdd.as_view(), name='order_add'),
    path('order_edit/<int:pk>/', OrderEdit.as_view(), name="order_edit"),
    path('order_delete/<int:pk>/', OrderDelete.as_view(), name="order_delete"),

    path('item_add/<int:order_pk>/', ItemAdd.as_view(), name='item_add'),
    path('item_edit/<int:pk>/', ItemEdit.as_view(), name="item_edit"),
    path('item_delete/<int:pk>/', ItemDelete.as_view(), name="item_delete"),

    path('comment_add/<int:order_pk>/', CommentAdd.as_view(), name='comment_add'),
    path('comment_edit/<int:pk>/', CommentEdit.as_view(), name="comment_edit"),
    path('comment_delete/<int:pk>/', CommentDelete.as_view(), name="comment_delete"),

    path('address_details/<int:order_pk>/', AddressDetails.as_view(), name='address_details'),
    path('address_add/<int:order_pk>/', AddressAdd.as_view(), name='address_add'),
    path('address_edit/<int:pk>/', AddressEdit.as_view(), name="address_edit"),
    path('address_delete/<int:pk>/', AddressDelete.as_view(), name="address_delete"),

    path('user_list/', UserList.as_view(), name="user_list"),
    path('user_add/', UserAdd.as_view(), name="user_add"),
    path('user_edit/<int:pk>/', UserEdit.as_view(), name="user_edit"),
    path('user_delete/<int:pk>/', UserDelete.as_view(), name="user_delete"),

    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name="logout"),

)

oms/orders/models.py
from django.db import models
from django.utils.translation import gettext as _


class Order(models.Model):
    VALUATION = _('Valuation')
    NEW = _('New')
    URGENT = _('Urgent')
    DRAWING = _('Drawing')
    INCOMPLETE = _('Incomplete')
    DESIGNED = _('Designed')
    EVAULATION = _('Evaluation')
    IMPROVEMENT = _('Improvement')
    ACCEPTED = _('Accepted')
    PRODUCTION = _('Production')
    PACKED = _('Packed')
    SENT = _('Sent')
    STATUS = [
        (VALUATION, _('Valuation')),
        (NEW, _('New')),
        (URGENT, _('Urgent')),
        (DRAWING, _('Drawing')),
        (INCOMPLETE, _('Incomplete')),
        (DESIGNED, _('Designed')),
        (EVAULATION, _('Evaluation')),
        (IMPROVEMENT, _('Improvement')),
        (ACCEPTED, _('Accepted')),
        (PRODUCTION, _('Production')),
        (PACKED, _('Packed')),
        (SENT, _('Sent')),
    ]

    # Seller
    MAREK = 'Marek'
    NATALIA = 'Natalia'
    JOANNA = 'Joanna'
    ANIA = 'Ania'
    SELLER = [
        (MAREK, 'Marek'),
        (NATALIA, 'Natalia'),
        (JOANNA, 'Joanna'),
        (ANIA, 'Ania'),
    ]

    # Designer
    MIKI = 'Miki'
    OLA = 'Ola'
    DESIGNER = [
        (MIKI, 'Miki'),
        (OLA, 'Ola'),
    ]

    date = models.DateTimeField(_('date'), auto_now_add=True)
    seller = models.CharField(_('seller'), max_length=20, choices=SELLER)
    customer = models.EmailField(_('customer'), max_length=260)
    designer = models.CharField(_('designer'), max_length=20, choices=DESIGNER, default=MIKI)
    status = models.CharField(_('status'), max_length=20, choices=STATUS, default=VALUATION)

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return self.customer


class Action(models.Model):
    name = models.CharField(max_length=30)
    translation = models.CharField(max_length=30)
    sequence = models.IntegerField()

    class Meta:
        ordering = ['sequence']

    def __str__(self):
        return self.name
        # return self.translation


class Item(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    # Name
    PREFAB = _('Prefab')
    NAMETAGS = _('Nametags')
    NUMBERS = _('Numbers')
    COVER = _('Covers')
    DIPLOMAS = _('Diplomas')
    STENCIL = _('Stencil')
    PLEXIGLASS = _('Plexiglass')
    CONTAINER = _('Container')
    BOARD = _('Board')
    STATUETTES = _('Statuettes')
    PLATES = _('Plates')
    LETTERS = _('Letters')

    NAME = [
        (PREFAB, _('Prefab')),
        (NAMETAGS, _('Nametags')),
        (NUMBERS, _('Numbers')),
        (COVER, _('Covers')),
        (DIPLOMAS, _('Diplomas')),
        (STENCIL, _('Stencil')),
        (PLEXIGLASS, _('Plexiglass')),
        (CONTAINER, _('Container')),
        (BOARD, _('Board')),
        (STATUETTES, _('Statuettes')),
        (PLATES, _('Plates')),
        (LETTERS, _('Letters')),
    ]

    # Material
    ALUMINIUM = _('Aluminium')
    LAMINATE = _('Laminate')
    DIBOND = _('Dibond')
    POLYCARBONATE = _('Polycarbonate')
    PLEXIGLASS = _('Plexiglass')
    CUSTOM = _('Custom')

    MATERIAL = [
        (ALUMINIUM, _('Aluminium')),
        (LAMINATE, _('Laminate')),
        (DIBOND, _('Dibond')),
        (POLYCARBONATE, _('Polycarbonate')),
        (PLEXIGLASS, _('Plexiglass')),
        (CUSTOM, _('Custom')),
    ]

    # Thickness
    ZERO_FIVE = '0,5'
    ZERO_EIGHT = '0,8'
    ONE_SIX = '1,6'
    TWO = '2'
    THREE = '3'
    FIVE = '5'
    OTHER = _('Other')

    THICKNESS = [
        (ZERO_FIVE, '0,5'),
        (ZERO_EIGHT, '0,8'),
        (ONE_SIX, '1,6'),
        (TWO, '2'),
        (THREE, '3'),
        (FIVE, '5'),
        (OTHER, _('Other')),
    ]

    # Color
    SILVER = _('Silver')
    GOLD = _('Gold')
    WHITE = _('White')
    BLACK = _('Black')
    TRANSPARENT = _('Transparent')
    CUSTOM = _('Custom')

    COLOR = [
        (SILVER, _('Silver')),
        (GOLD, _('Gold')),
        (WHITE, _('White')),
        (BLACK, _('Black')),
        (TRANSPARENT, _('Transparent')),
        (CUSTOM, _('Custom')),
    ]

    # Dimensions
    OUTSIDE = _('Outside')
    INSIDE = _('Inside')

    DIMENSIONS = [
        (OUTSIDE, _('Outside')),
        (INSIDE, _('Inside')),
    ]

    # Fastening
    PIN = _('Pin')
    MAGNET = _('Magnet')
    GLUE = _('Glue')
    HOLES = _('Holes')
    WITHOUT = _('Without')
    CUSTOM = _('Custom')

    FASTENING = [
        (PIN, _('Pin')),
        (MAGNET, _('Magnet')),
        (GLUE, _('Glue')),
        (HOLES, _('Holes')),
        (WITHOUT, _('Without')),
        (CUSTOM, _('Custom')),
    ]

    # Mark
    PRINT = _('Print')
    ENGRAVER = _('Engraver')
    FOIL = _('Foil')
    STICKER = _('Sticker')
    OUTSOURCE = _('Outsource')
    WITHOUT = _('Without')
    CUSTOM = _('Custom')

    MARK = [
        (PRINT, _('Print')),
        (ENGRAVER, _('Engraver')),
        (FOIL, _('Foil')),
        (STICKER, _('Sticker')),
        (OUTSOURCE, _('Outsource')),
        (WITHOUT, _('Without')),
        (CUSTOM, _('Custom')),
    ]

    name = models.CharField(_('name'), max_length=30, choices=NAME)
    material = models.CharField(_('material'), max_length=50, choices=MATERIAL)
    thickness = models.CharField(_('thickness'), max_length=10, choices=THICKNESS)
    color = models.CharField(_('color'), max_length=50, choices=COLOR)
    dimensions = models.CharField(_('dimensions'), max_length=30, choices=DIMENSIONS, null=True, blank=True,
                                  default=OUTSIDE)
    width = models.IntegerField(_('width'))
    height = models.IntegerField(_('height'))
    depth = models.IntegerField(_('depth'), null=True, blank=True)
    fastening = models.CharField(_('fastening'), max_length=30, choices=FASTENING)

    hole = models.CharField(_('hole'), max_length=20, null=True, blank=True)
    rounding = models.CharField(_('rounding'), max_length=10, null=True, blank=True)
    mark = models.CharField(_('mark'), max_length=50, choices=MARK)
    quantity = models.IntegerField(_('quantity'))
    description = models.TextField(_('description'), null=True, blank=True, default=None)

    actions = models.ManyToManyField(Action, verbose_name=_("Action"))

    def __str__(self):
        return self.name


class Comment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    message = models.TextField(_('message'))

    def __str__(self):
        return self.date


class Address(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    customer = models.CharField(_('customer'), max_length=255)
    street = models.CharField(_('street'), max_length=100)
    zip_code = models.CharField(_('zip code'), max_length=6)
    city = models.CharField(_('city'), max_length=30)
    shipment_date = models.DateField(_('shipment date'), )
    shipment_comment = models.TextField(_('shipment comment'), blank=True)
    phone_number = models.CharField(_('phone number'), max_length=12)

    def __str__(self):
        return self.customer

oms/orders/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Order, Item, Comment, Address
from .forms import OrderAddForm, ItemAddForm, CommentAddForm, SearchForm, AddressAddForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, RedirectView, DeleteView, UpdateView, ListView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db.models import Q


class OrderList(View):
    def get(self, request):
        orders = Order.objects.order_by('date').exclude(status="Sent")
        context = {"orders": orders}
        return render(request, 'orders/order_list.html', context)


class Archive(View):
    def get(self, request):
        orders_shipped = Order.objects.filter(status="Sent")
        context = {"orders_shipped": orders_shipped}
        return render(request, 'orders/archive.html', context)


class Stats(View):
    def get(self, request):
        marek = Order.objects.filter(seller="Marek").exclude(status="Sent").count()
        natalia = Order.objects.filter(seller="Natalia").exclude(status="Sent").count()
        joanna = Order.objects.filter(seller="Joanna").exclude(status="Sent").count()
        ania = Order.objects.filter(seller="Ania").exclude(status="Sent").count()
        miki = Order.objects.filter(designer='Miki').filter(
            Q(status='New') | Q(status='Urgent') | Q(status='Drawing') | Q(status='Incomplete') | Q(
                status='Improvement')).count()
        ola = Order.objects.filter(designer='Ola').filter(
            Q(status='New') | Q(status='Urgent') | Q(status='Drawing') | Q(status='Incomplete') | Q(
                status='Improvement')).count()
        context = {"marek": marek, "natalia": natalia, "joanna": joanna, "ania": ania, "miki": miki, "ola": ola}
        return render(request, 'orders/stats.html', context)


class Info(View):
    def get(self, request):
        return render(request, 'orders/info.html')


class OrderDetails(View):
    def get(self, request, order_pk):
        order = Order.objects.get(pk=order_pk)
        comments = Comment.objects.filter(order=order_pk).order_by('date')
        items = Item.objects.filter(order=order_pk).order_by('pk')
        context = {"order": order, "items": items, "comments": comments}
        return render(request, 'orders/order_details.html', context)


class OrderAdd(PermissionRequiredMixin, CreateView):
    permission_required = 'orders.add_order'
    model = Order
    form_class = OrderAddForm
    template_name = 'orders/order_add.html'
    success_url = reverse_lazy('order_list')


class OrderDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'orders.delete_order'
    model = Order
    success_url = reverse_lazy('order_list')


class OrderEdit(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Order
    form_class = OrderAddForm
    template_name_suffix = '_edit'
    success_url = reverse_lazy('order_list')


class ItemAdd(PermissionRequiredMixin, CreateView):
    permission_required = 'orders.add_item'
    model = Item
    form_class = ItemAddForm
    template_name = 'orders/item_add.html'
    success_url = "/order_details/{order_id}"

    def get_initial(self):
        order_pk = self.kwargs["order_pk"]
        data = super().get_initial()
        data["order"] = Order.objects.get(pk=order_pk)
        return data


class ItemDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'orders.delete_item'
    model = Item
    success_url = "/order_details/{order_id}"


class ItemEdit(PermissionRequiredMixin, UpdateView):
    permission_required = 'orders.change_item'
    model = Item
    form_class = ItemAddForm
    template_name_suffix = '_edit'
    success_url = "/order_details/{order_id}"


class CommentAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Comment
    form_class = CommentAddForm
    template_name = 'orders/comment_add.html'
    success_url = "/order_details/{order_id}"

    def get_initial(self):
        order_pk = self.kwargs["order_pk"]
        data = super().get_initial()
        data["order"] = Order.objects.get(pk=order_pk)
        return data


class CommentDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Comment
    success_url = "/order_details/{order_id}"


class CommentEdit(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Comment
    form_class = CommentAddForm
    template_name_suffix = '_edit'
    success_url = "/order_details/{order_id}"


class OrderSearch(View):
    template_name = "orders/order_search.html"

    def get(self, request, *args, **kwargs):
        form = SearchForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = SearchForm(request.POST)
        if form.is_valid():
            customer = form.cleaned_data['customer']
            orders = Order.objects.filter(customer__icontains=customer)
            context = {'form': form, 'orders': orders}
            return render(request, self.template_name, context)
        else:
            return render(request, self.template_name, {'form': form})


class AddressDetails(LoginRequiredMixin, View):
    login_url = '/login/'

    def get(self, request, order_pk):
        order = Order.objects.get(pk=order_pk)
        try:
            address = Address.objects.get(order=order_pk)
        except:
            address = None

        context = {"order": order, "address": address}
        return render(request, 'orders/address_details.html', context)


class AddressAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Address
    form_class = AddressAddForm
    template_name = 'orders/address_add.html'
    success_url = "/address_details/{order_id}"

    def get_initial(self):
        order_pk = self.kwargs["order_pk"]
        data = super().get_initial()
        data["order"] = Order.objects.get(pk=order_pk)
        return data


class AddressDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    model = Address
    success_url = "/address_details/{order_id}"


class AddressEdit(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    model = Address
    form_class = AddressAddForm
    template_name_suffix = '_edit'
    success_url = "/address_details/{order_id}"

oms/orders/templates/orders/address_add.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Add address" %}</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

</br>
<button type="submit" class="icon"><i class="bi-check"></i></button></a>

</form>
</br>

{% endblock %}

oms/orders/templates/orders/address_details.html
{% extends 'base.html' %}
{% block content %}
    {% load i18n %}
    <h2>{% trans "Shipping address" %}</h2>

    <a href='/order_details/{{ order.pk}}' style="color: var(--light)">{{ order.customer }}</a>

    </br></br>

    {% if perms.orders.add_address %}
        {% if address == None %}
            <a href='/address_add/{{ order.pk }}/'><button class="icon"><i class="bi-plus"></i></button></a>
        {% else %}
            <a href='/address_edit/{{ address.pk }}'><button class="icon"><i class="bi-pencil"></i></button></a>
        {% endif %}
    {% endif %}


    </br></br></br>

        {% if address != None %}
        <div class="item">
            {% trans address.customer %} </br>
            {% trans address.street %} </br>
            {% trans address.zip_code %} {% trans address.city %} </br>

            </br>

            {% trans "Shipment date" %}: {{ address.shipment_date }} </br>
            {% trans "Phone number" %}: {{ address.phone_number }} </br>

            </br>

            {% if address.shipment_comment != None %}
            {{ address.shipment_comment }}
            {% endif %}

        </div>
        {% endif %}

{% endblock %}

oms/orders/templates/orders/address_edit.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Edit address" %}</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

</br>
<button type="submit" class="icon"><i class="bi-check"></i></button></a>

{% if perms.orders.delete_address %}
<a href='/address_delete/{{ address.pk }}'><button type="button" class="icon"><i class="bi-trash3"></i></button></a>
{% endif %}

</form>
</br></br>
{% endblock %}

oms/orders/templates/orders/comment_add.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Add comment" %}</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

</br>
<button type="submit" class="icon"><i class="bi-check"></i></button></a>

</form>
</br>

{% endblock %}

oms/orders/templates/orders/comment_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Delete comment" %}</h2>

{{ comment.message }}
</br></br>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

<button type="submit" class="icon"><i class="bi-check"></i></button></a>

</form>

{% endblock %}

oms/orders/templates/orders/info.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}

    <h2>{%  trans "Project description" %}</h2>
    <mark>{%  trans "Web application for managing orders" %}</mark></br>
    </br>
    User manual

{% endblock %}

oms/orders/templates/orders/item_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Delete item" %}</h2>

{{ item.name }}
</br></br>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

<button type="submit" class="icon"><i class="bi-check"></i></button></a>

</form>

{% endblock %}

oms/orders/templates/orders/item_edit.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Edit item" %}</h2>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

</br>

<button type="submit" class="icon"><i class="bi-check"></i></button></a>

{% if perms.orders.delete_item %}
<a href='/item_delete/{{ item.pk }}'><button type="button" class="icon"><i class="bi-trash3"></i></button></a>
{% endif %}

</form>
</br></br>
{% endblock %}

oms/orders/templates/orders/menu.html
{% extends 'base.html' %}
{% block content %}

<h2 style="text-transform: capitalize">
{% if user.username %}
    {{ user.username }}
{% else %}
    Menu
{% endif %}
</h2>

{% if user.username %}
    <a href='{% url "logout" %}'><button type="button">Logout</button></a>
{% else %}
    <a href='{% url "login" %}'><button type="button">Login</button></a>
{% endif %}

<a href='/user_list/'><button type="button">Users</button></a>
<button type="button" value="Previous Page" onClick="javascript:history.go(-1);">Back</button>

</br></br>

    <h3>Opis projektu</h3>
    <mark>Aplikacja webowa do zarządzania zamówieniami</mark></br>
    </br>
    Wykonałem ją dla dotychczasowego pracodawcy.</br>
    Zastępuje ręczne uzupełnianie arkuszy oraz drukowanie zleceń.</br>
    Opracowany system usprawnia komunikację pomiędzy działem handlowym, graficznym i produkcyjnym.</br>
    Rozwiązuje problem błędów komunikacyjnych dzięki weryfikacji danych.</br>
    </br>
    Podstawą programu jest tworzenie zamówień i monitorowanie ich statusu realizacji.</br>
    Każdy z pracowników ma własne konto, a poprzez filtrowanie system wyświetla użytkownikowi tylko niezbędne dane.</br>
    Automatyzacja procesów zachodząca w aplikacji znacznie redukuje ilość czynności potrzebnych do zrealizowania zamówienia.</br>

{% endblock %}

oms/orders/templates/orders/order_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Delete order" %}</h2>

{{ order.customer }}
</br></br>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}

<button type="submit" class="icon"><i class="bi-check"></i></button></a>

</form>

{% endblock %}

oms/orders/templates/orders/order_details.html
{% extends 'base.html' %}
{% block content %}
{% load i18n %}
<h2>{%  trans "Order details" %}</h2>

{{ order.customer }}

</br></br>

{% if perms.orders.add_item %}
<a href='/item_add/{{ order.pk }}/'><button class="icon"><i class="bi-plus"></i></button></a>
{% endif %}
<a href='/comment_add/{{ order.pk }}/'><button class="icon"><i class="bi-chat"></i></button></a>
<a href='/address_details/{{ order.pk }}/'><button class="icon"><i class="bi-geo-alt"></i></button></a>


</br></br>

{% for comment in comments %}
    {% if comment != None %}
        <a href='/comment_edit/{{ comment.pk }}'>{{ comment.date|date:'H:i' }}: {{ comment.message }}</a></br></br>
    {%  endif %}
{% endfor %}

{% for item in items %}
<div class="item">
<table class="table">

    <thead>
    <tr>
        <th data-label="name" colspan="2">{% trans item.name %}</th>
    </tr>
    </thead>

    <tr>
        <td>{%  trans "Material" %}:</td>
        <td data-label="material">{% trans item.material %}</td>
    </tr>

     <tr>
        <td>{%  trans "Thickness" %}:</td>
        <td data-label="thickness">{% trans item.thickness %} mm</td>
    </tr>

    <tr>
        <td>{%  trans "Color" %}:</td>
        <td data-label="color">{% trans item.color %}</td>
    </tr>

    {% if item.dimensions != None %}
    <tr>
        <td>{%  trans "Dimensions" %}:</td>
        <td data-label="dimensions">{% trans item.dimensions %}</td>
    </tr>
    {%  endif %}

    <tr>
        <td>{%  trans "Width" %}:</td>
        <td data-label="width">{{ item.width }} mm</td>
    </tr>

    <tr>
        <td>{%  trans "Height" %}:</td>
        <td data-label="height">{{ item.height }} mm</td>
    </tr>

    {% if item.depth != None %}
    <tr>
        <td>{%  trans "Depth" %}:</td>
        <td data-label="depth">{{ item.depth }} mm</td>
    </tr>
    {%  endif %}

    <tr>
        <td>{%  trans "Fastening" %}:</td>
        <td data-label="fastening">{% trans item.fastening %}</td>
    </tr>

    {% if item.hole != None %}
    <tr>
        <td>{%  trans "Hole" %}:</td>
        <td data-label="hole">{% trans item.hole %} mm</td>
    </tr>
    {%  endif %}

    {% if item.rounding != None %}
    <tr>
        <td>{%  trans "Rounding" %}:</td>
        <td data-label="rounding">{% trans item.rounding %}</td>
    </tr>
    {%  endif %}

    {% if item.mark != None %}
    <tr>
        <td>{%  trans "Mark" %}:</td>
        <td data-label="mark">{% trans item.mark %}</td>
    </tr>
    {%  endif %}

    <tr>
        <td>{%  trans "Quantity" %}:</td>
        <td data-label="quantity">{{ item.quantity }}</td>
    </tr>

    {% if item.description %}
    <tr><td data-label="description" colspan="2" class="description">{{ item.description }}</td></tr>
    {%  endif %}

    <tr><th colspan="2">
        {% for actions in item.actions.all %}
            {% if LANGUAGE_CODE == "en" %}
                {%  trans actions.name %}
            {%  else %}
                {%  trans actions.translation %}
            {% endif %}
        {% endfor %}
    </th></tr>

{#    {% if perms.orders.change_item %}#}
    <tr>
        <td colspan="2"><a href='/item_edit/{{ item.pk }}'><button class="icon"><i class="bi-pencil"></i></button></a></td>
    </tr>
{#    {% endif %}#}

</table></br>
</div>
{% endfor %}

{% endblock %}

oms/orders/templates/orders/order_list.html
{% extends 'base.html' %}
{% block content %}
    {% load i18n %}

    <h2></h2>

    <table class="table">

        <thead>
        <tr>
            <th scope="col">{% trans "date" %}</th>
            <th scope="col">{% trans "seller" %}</th>
            <th scope="col">{% trans "customer" %}</th>
            <th scope="col">{% trans "designer" %}</th>
            <th scope="col">Status</th>

            <th scope="col">
                {#        {% if perms.orders.add_order %}#}
                <a href='/order_add/'>
                    <button class="icon"><i class="bi-plus"></i></button>
                </a>
                {#        {% endif %}#}
            </th>

        </tr>
        </thead>

        <tbody>
        {% for order in orders %}
            <tr>
                <td data-label="date<">{{ order.date }}</td>
                <td data-label="seller">{{ order.seller }}</td>
                <td data-label="customer"><a href='/order_details/{{ order.pk }}'
                                             style="color: var(--light)">{{ order.customer }}</a></td>
                <td data-label="designer">{{ order.designer }}</td>
                <td data-label="status" class="status" id="status">{% trans order.status %}</td>
                <td><a href='/order_edit/{{ order.pk }}'>
                    <button class="icon"><i class="bi-pencil"></i></button>
                </a></td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
    </br>

{% endblock %}